/*
 * This file was automatically generated by `./src/chains/ethereum/console.log/scripts/generate.ts`; do not edit. */

import { address, bool, bytes, int256, string, uint256, fixedBytes } from "./handlers";

export const signatureMap = new Map([
  // log()
  [1368866505, []],

  // log(address)
  [741264322, [address]],

  // log(bool)
  [843419373, [bool]],

  // log(string)
  [1093685164, [string]],

  // log(uint256)
  [4163653873, [uint256]],

  // log(uint)
  [4122065833, [uint256]],

  // log(bytes)
  [199720790, [bytes]],

  // log(int256)
  [760966329, [uint256]],

  // log(int)
  [1309416733, [int256]],

  // log(bytes1)
  [1847107880, [fixedBytes(1)]],

  // log(bytes2)
  [3921027734, [fixedBytes(2)]],

  // log(bytes3)
  [763578662, [fixedBytes(3)]],

  // log(bytes4)
  [3764340945, [fixedBytes(4)]],

  // log(bytes5)
  [2793701517, [fixedBytes(5)]],

  // log(bytes6)
  [2927928721, [fixedBytes(6)]],

  // log(bytes7)
  [1322614312, [fixedBytes(7)]],

  // log(bytes8)
  [1334060334, [fixedBytes(8)]],

  // log(bytes9)
  [2428341456, [fixedBytes(9)]],

  // log(bytes10)
  [20780939, [fixedBytes(10)]],

  // log(bytes11)
  [67127854, [fixedBytes(11)]],

  // log(bytes12)
  [2258660029, [fixedBytes(12)]],

  // log(bytes13)
  [2488442420, [fixedBytes(13)]],

  // log(bytes14)
  [2456219775, [fixedBytes(14)]],

  // log(bytes15)
  [3667227872, [fixedBytes(15)]],

  // log(bytes16)
  [1717330180, [fixedBytes(16)]],

  // log(bytes17)
  [866084666, [fixedBytes(17)]],

  // log(bytes18)
  [3302112666, [fixedBytes(18)]],

  // log(bytes19)
  [1584093747, [fixedBytes(19)]],

  // log(bytes20)
  [1367925737, [fixedBytes(20)]],

  // log(bytes21)
  [3923391840, [fixedBytes(21)]],

  // log(bytes22)
  [3589990556, [fixedBytes(22)]],

  // log(bytes23)
  [2879508237, [fixedBytes(23)]],

  // log(bytes24)
  [4055063348, [fixedBytes(24)]],

  // log(bytes25)
  [193248344, [fixedBytes(25)]],

  // log(bytes26)
  [4172368369, [fixedBytes(26)]],

  // log(bytes27)
  [976705501, [fixedBytes(27)]],

  // log(bytes28)
  [3358255854, [fixedBytes(28)]],

  // log(bytes29)
  [1265222613, [fixedBytes(29)]],

  // log(bytes30)
  [3994207469, [fixedBytes(30)]],

  // log(bytes31)
  [3263516050, [fixedBytes(31)]],

  // log(bytes32)
  [666357637, [fixedBytes(32)]],

  // log(address,address)
  [3673216170, [address, address]],

  // log(address,bool)
  [1974863315, [address, bool]],

  // log(address,string)
  [1973388987, [address, string]],

  // log(address,uint256)
  [2198464680, [address, uint256]],

  // log(address,uint)
  [574869411, [address, uint256]],

  // log(bool,address)
  [2235320393, [bool, address]],

  // log(bool,bool)
  [705760899, [bool, bool]],

  // log(bool,string)
  [2414527781, [bool, string]],

  // log(bool,uint256)
  [965833939, [bool, uint256]],

  // log(bool,uint)
  [910912146, [bool, uint256]],

  // log(string,address)
  [832238387, [string, address]],

  // log(string,bool)
  [3283441205, [string, bool]],

  // log(string,string)
  [1264337527, [string, string]],

  // log(string,uint256)
  [3054400204, [string, uint256]],

  // log(string,uint)
  [2534451664, [string, uint256]],

  // log(uint256,address)
  [1764191366, [uint256, address]],

  // log(uint,address)
  [1491830284, [uint256, address]],

  // log(uint256,bool)
  [480083635, [uint256, bool]],

  // log(uint,bool)
  [510514412, [uint256, bool]],

  // log(uint256,string)
  [1681903839, [uint256, string]],

  // log(uint,string)
  [262402885, [uint256, string]],

  // log(uint256,uint256)
  [4133908826, [uint256, uint256]],

  // log(uint,uint)
  [1812949376, [uint256, uint256]],

  // log(address,address,address)
  [25986242, [address, address, address]],

  // log(address,address,bool)
  [4070990470, [address, address, bool]],

  // log(address,address,string)
  [7426238, [address, address, string]],

  // log(address,address,uint256)
  [402547077, [address, address, uint256]],

  // log(address,address,uint)
  [1815506290, [address, address, uint256]],

  // log(address,bool,address)
  [4044790253, [address, bool, address]],

  // log(address,bool,bool)
  [3951234194, [address, bool, bool]],

  // log(address,bool,string)
  [555898316, [address, bool, string]],

  // log(address,bool,uint256)
  [2622462459, [address, bool, uint256]],

  // log(address,bool,uint)
  [742821141, [address, bool, uint256]],

  // log(address,string,address)
  [4035396840, [address, string, address]],

  // log(address,string,bool)
  [3473018801, [address, string, bool]],

  // log(address,string,string)
  [4218888805, [address, string, string]],

  // log(address,string,uint256)
  [1742565361, [address, string, uint256]],

  // log(address,string,uint)
  [484110986, [address, string, uint256]],

  // log(address,uint256,address)
  [2076235848, [address, uint256, address]],

  // log(address,uint,address)
  [2548867988, [address, uint256, address]],

  // log(address,uint256,bool)
  [1736575400, [address, uint256, bool]],

  // log(address,uint,bool)
  [3846889796, [address, uint256, bool]],

  // log(address,uint256,string)
  [2717051050, [address, uint256, string]],

  // log(address,uint,string)
  [3136907337, [address, uint256, string]],

  // log(address,uint256,uint256)
  [3063663350, [address, uint256, uint256]],

  // log(address,uint,uint)
  [2273710942, [address, uint256, uint256]],

  // log(bool,address,address)
  [3530962535, [bool, address, address]],

  // log(bool,address,bool)
  [415876934, [bool, address, bool]],

  // log(bool,address,string)
  [3734671984, [bool, address, string]],

  // log(bool,address,uint256)
  [1601936123, [bool, address, uint256]],

  // log(bool,address,uint)
  [3950005167, [bool, address, uint256]],

  // log(bool,bool,address)
  [276362893, [bool, bool, address]],

  // log(bool,bool,bool)
  [1349555864, [bool, bool, bool]],

  // log(bool,bool,string)
  [626391622, [bool, bool, string]],

  // log(bool,bool,uint256)
  [317855234, [bool, bool, uint256]],

  // log(bool,bool,uint)
  [2954061243, [bool, bool, uint256]],

  // log(bool,string,address)
  [2509355347, [bool, string, address]],

  // log(bool,string,bool)
  [3686056519, [bool, string, bool]],

  // log(bool,string,string)
  [2960557183, [bool, string, string]],

  // log(bool,string,uint256)
  [278130193, [bool, string, uint256]],

  // log(bool,string,uint)
  [3224906412, [bool, string, uint256]],

  // log(bool,uint256,address)
  [143587794, [bool, uint256, address]],

  // log(bool,uint,address)
  [3302110471, [bool, uint256, address]],

  // log(bool,uint256,bool)
  [3906927529, [bool, uint256, bool]],

  // log(bool,uint,bool)
  [464374251, [bool, uint256, bool]],

  // log(bool,uint256,string)
  [3288086896, [bool, uint256, string]],

  // log(bool,uint,string)
  [3359211184, [bool, uint256, string]],

  // log(bool,uint256,uint256)
  [923808615, [bool, uint256, uint256]],

  // log(bool,uint,uint)
  [995886048, [bool, uint256, uint256]],

  // log(string,address,address)
  [4243355104, [string, address, address]],

  // log(string,address,bool)
  [3374145236, [string, address, bool]],

  // log(string,address,string)
  [3773410639, [string, address, string]],

  // log(string,address,uint256)
  [220641573, [string, address, uint256]],

  // log(string,address,uint)
  [130552343, [string, address, uint256]],

  // log(string,bool,address)
  [2469116728, [string, bool, address]],

  // log(string,bool,bool)
  [2232122070, [string, bool, bool]],

  // log(string,bool,string)
  [3801674877, [string, bool, string]],

  // log(string,bool,uint256)
  [3378075862, [string, bool, uint256]],

  // log(string,bool,uint)
  [689682896, [string, bool, uint256]],

  // log(string,string,address)
  [2515337621, [string, string, address]],

  // log(string,string,bool)
  [2967534005, [string, string, bool]],

  // log(string,string,string)
  [753761519, [string, string, string]],

  // log(string,string,uint256)
  [1478619041, [string, string, uint256]],

  // log(string,string,uint)
  [4083337817, [string, string, uint256]],

  // log(string,uint256,address)
  [478069832, [string, uint256, address]],

  // log(string,uint,address)
  [3817119609, [string, uint256, address]],

  // log(string,uint256,bool)
  [3396809649, [string, uint256, bool]],

  // log(string,uint,bool)
  [4043501061, [string, uint256, bool]],

  // log(string,uint256,string)
  [1500569737, [string, uint256, string]],

  // log(string,uint,string)
  [2750793529, [string, uint256, string]],

  // log(string,uint256,uint256)
  [3393701099, [string, uint256, uint256]],

  // log(string,uint,uint)
  [2526862595, [string, uint256, uint256]],

  // log(uint256,address,address)
  [3170737120, [uint256, address, address]],

  // log(uint,address,address)
  [2104993307, [uint256, address, address]],

  // log(uint256,address,bool)
  [2607726658, [uint256, address, bool]],

  // log(uint,address,bool)
  [2060456590, [uint256, address, bool]],

  // log(uint256,address,string)
  [1674265081, [uint256, address, string]],

  // log(uint,address,string)
  [3464692859, [uint256, address, string]],

  // log(uint256,address,uint256)
  [1520131797, [uint256, address, uint256]],

  // log(uint,address,uint)
  [2286109610, [uint256, address, uint256]],

  // log(uint256,bool,address)
  [889741179, [uint256, bool, address]],

  // log(uint,bool,address)
  [1112473535, [uint256, bool, address]],

  // log(uint256,bool,bool)
  [544310864, [uint256, bool, bool]],

  // log(uint,bool,bool)
  [3587091680, [uint256, bool, bool]],

  // log(uint256,bool,string)
  [2239189025, [uint256, bool, string]],

  // log(uint,bool,string)
  [2332955902, [uint256, bool, string]],

  // log(uint256,bool,uint256)
  [537493524, [uint256, bool, uint256]],

  // log(uint,bool,uint)
  [1515034914, [uint256, bool, uint256]],

  // log(uint256,string,address)
  [2063255897, [uint256, string, address]],

  // log(uint,string,address)
  [529592906, [uint256, string, address]],

  // log(uint256,string,bool)
  [1290643290, [uint256, string, bool]],

  // log(uint,string,bool)
  [1185403086, [uint256, string, bool]],

  // log(uint256,string,string)
  [2970968351, [uint256, string, string]],

  // log(uint,string,string)
  [1062716053, [uint256, string, string]],

  // log(uint256,string,uint256)
  [933920076, [uint256, string, uint256]],

  // log(uint,string,uint)
  [1533929535, [uint256, string, uint256]],

  // log(uint256,uint256,address)
  [1553380145, [uint256, uint256, address]],

  // log(uint,uint,address)
  [3191032091, [uint256, uint256, address]],

  // log(uint256,uint256,bool)
  [1197922930, [uint256, uint256, bool]],

  // log(uint,uint,bool)
  [1733758967, [uint256, uint256, bool]],

  // log(uint256,uint256,string)
  [1909476082, [uint256, uint256, string]],

  // log(uint,uint,string)
  [2104037094, [uint256, uint256, string]],

  // log(uint256,uint256,uint256)
  [3522001468, [uint256, uint256, uint256]],

  // log(uint,uint,uint)
  [3884059252, [uint256, uint256, uint256]],

  // log(address,address,address,address)
  [1717301556, [address, address, address, address]],

  // log(address,address,address,bool)
  [238520724, [address, address, address, bool]],

  // log(address,address,address,string)
  [4161329696, [address, address, address, string]],

  // log(address,address,address,uint256)
  [2485456247, [address, address, address, uint256]],

  // log(address,address,address,uint)
  [3982404743, [address, address, address, uint256]],

  // log(address,address,bool,address)
  [2669396846, [address, address, bool, address]],

  // log(address,address,bool,bool)
  [752096074, [address, address, bool, bool]],

  // log(address,address,bool,string)
  [2858762440, [address, address, bool, string]],

  // log(address,address,bool,uint256)
  [963766156, [address, address, bool, uint256]],

  // log(address,address,bool,uint)
  [2513854225, [address, address, bool, uint256]],

  // log(address,address,string,address)
  [2406706454, [address, address, string, address]],

  // log(address,address,string,bool)
  [1863997774, [address, address, string, bool]],

  // log(address,address,string,string)
  [566079269, [address, address, string, string]],

  // log(address,address,string,uint256)
  [4011651047, [address, address, string, uint256]],

  // log(address,address,string,uint)
  [69767936, [address, address, string, uint256]],

  // log(address,address,uint256,address)
  [2376523509, [address, address, uint256, address]],

  // log(address,address,uint,address)
  [3603321462, [address, address, uint256, address]],

  // log(address,address,uint256,bool)
  [2604815586, [address, address, uint256, bool]],

  // log(address,address,uint,bool)
  [3270936812, [address, address, uint256, bool]],

  // log(address,address,uint256,string)
  [4256496016, [address, address, uint256, string]],

  // log(address,address,uint,string)
  [2647731885, [address, address, uint256, string]],

  // log(address,address,uint256,uint256)
  [3193255041, [address, address, uint256, uint256]],

  // log(address,address,uint,uint)
  [1425929188, [address, address, uint256, uint256]],

  // log(address,bool,address,address)
  [1711502813, [address, bool, address, address]],

  // log(address,bool,address,bool)
  [2801077007, [address, bool, address, bool]],

  // log(address,bool,address,string)
  [769095910, [address, bool, address, string]],

  // log(address,bool,address,uint256)
  [2807847390, [address, bool, address, uint256]],

  // log(address,bool,address,uint)
  [3698398930, [address, bool, address, uint256]],

  // log(address,bool,bool,address)
  [3476636805, [address, bool, bool, address]],

  // log(address,bool,bool,bool)
  [3401856121, [address, bool, bool, bool]],

  // log(address,bool,bool,string)
  [3754205928, [address, bool, bool, string]],

  // log(address,bool,bool,uint256)
  [2353946086, [address, bool, bool, uint256]],

  // log(address,bool,bool,uint)
  [3484780374, [address, bool, bool, uint256]],

  // log(address,bool,string,address)
  [436029782, [address, bool, string, address]],

  // log(address,bool,string,bool)
  [1353532957, [address, bool, string, bool]],

  // log(address,bool,string,string)
  [1197235251, [address, bool, string, string]],

  // log(address,bool,string,uint256)
  [2162598411, [address, bool, string, uint256]],

  // log(address,bool,string,uint)
  [2652011374, [address, bool, string, uint256]],

  // log(address,bool,uint256,address)
  [3438776481, [address, bool, uint256, address]],

  // log(address,bool,uint,address)
  [227337758, [address, bool, uint256, address]],

  // log(address,bool,uint256,bool)
  [3294903840, [address, bool, uint256, bool]],

  // log(address,bool,uint,bool)
  [2244855215, [address, bool, uint256, bool]],

  // log(address,bool,uint256,string)
  [178704301, [address, bool, uint256, string]],

  // log(address,bool,uint,string)
  [2606272204, [address, bool, uint256, string]],

  // log(address,bool,uint256,uint256)
  [946861556, [address, bool, uint256, uint256]],

  // log(address,bool,uint,uint)
  [3255869470, [address, bool, uint256, uint256]],

  // log(address,string,address,address)
  [221706784, [address, string, address, address]],

  // log(address,string,address,bool)
  [233909110, [address, string, address, bool]],

  // log(address,string,address,string)
  [4158874181, [address, string, address, string]],

  // log(address,string,address,uint256)
  [1166009295, [address, string, address, uint256]],

  // log(address,string,address,uint)
  [2350461865, [address, string, address, uint256]],

  // log(address,string,bool,address)
  [542667202, [address, string, bool, address]],

  // log(address,string,bool,bool)
  [1595759775, [address, string, bool, bool]],

  // log(address,string,bool,string)
  [3154862590, [address, string, bool, string]],

  // log(address,string,bool,uint256)
  [1365129398, [address, string, bool, uint256]],

  // log(address,string,bool,uint)
  [3877655068, [address, string, bool, uint256]],

  // log(address,string,string,address)
  [2689478535, [address, string, string, address]],

  // log(address,string,string,bool)
  [900007711, [address, string, string, bool]],

  // log(address,string,string,string)
  [1560462603, [address, string, string, string]],

  // log(address,string,string,uint256)
  [362776871, [address, string, string, uint256]],

  // log(address,string,string,uint)
  [2706362425, [address, string, string, uint256]],

  // log(address,string,uint256,address)
  [1662531192, [address, string, uint256, address]],

  // log(address,string,uint,address)
  [3755464715, [address, string, uint256, address]],

  // log(address,string,uint256,bool)
  [251125840, [address, string, uint256, bool]],

  // log(address,string,uint,bool)
  [2116357467, [address, string, uint256, bool]],

  // log(address,string,uint256,string)
  [1149776040, [address, string, uint256, string]],

  // log(address,string,uint,string)
  [1561552329, [address, string, uint256, string]],

  // log(address,string,uint256,uint256)
  [499704248, [address, string, uint256, uint256]],

  // log(address,string,uint,uint)
  [2764647008, [address, string, uint256, uint256]],

  // log(address,uint256,address,address)
  [1200430178, [address, uint256, address, address]],

  // log(address,uint,address,address)
  [3961816175, [address, uint256, address, address]],

  // log(address,uint256,address,bool)
  [2713504179, [address, uint256, address, bool]],

  // log(address,uint,address,bool)
  [4051804649, [address, uint256, address, bool]],

  // log(address,uint256,address,string)
  [497649386, [address, uint256, address, string]],

  // log(address,uint,address,string)
  [1567749022, [address, uint256, address, string]],

  // log(address,uint256,address,uint256)
  [269444366, [address, uint256, address, uint256]],

  // log(address,uint,address,uint)
  [2782496616, [address, uint256, address, uint256]],

  // log(address,uint256,bool,address)
  [2736520652, [address, uint256, bool, address]],

  // log(address,uint,bool,address)
  [602229106, [address, uint256, bool, address]],

  // log(address,uint256,bool,bool)
  [1005970743, [address, uint256, bool, bool]],

  // log(address,uint,bool,bool)
  [4272018778, [address, uint256, bool, bool]],

  // log(address,uint256,bool,string)
  [3316483577, [address, uint256, bool, string]],

  // log(address,uint,bool,string)
  [2391690869, [address, uint256, bool, string]],

  // log(address,uint256,bool,uint256)
  [586594713, [address, uint256, bool, uint256]],

  // log(address,uint,bool,uint)
  [1770996626, [address, uint256, bool, uint256]],

  // log(address,uint256,string,address)
  [1547898183, [address, uint256, string, address]],

  // log(address,uint,string,address)
  [3698927108, [address, uint256, string, address]],

  // log(address,uint256,string,bool)
  [3474460764, [address, uint256, string, bool]],

  // log(address,uint,string,bool)
  [2751614737, [address, uint256, string, bool]],

  // log(address,uint256,string,string)
  [2292761606, [address, uint256, string, string]],

  // log(address,uint,string,string)
  [2119616147, [address, uint256, string, string]],

  // log(address,uint256,string,uint256)
  [3204577425, [address, uint256, string, uint256]],

  // log(address,uint,string,uint)
  [4111650715, [address, uint256, string, uint256]],

  // log(address,uint256,uint256,address)
  [551786573, [address, uint256, uint256, address]],

  // log(address,uint,uint,address)
  [519451700, [address, uint256, uint256, address]],

  // log(address,uint256,uint256,bool)
  [1727118439, [address, uint256, uint256, bool]],

  // log(address,uint,uint,bool)
  [3964381346, [address, uint256, uint256, bool]],

  // log(address,uint256,uint256,string)
  [1244184599, [address, uint256, uint256, string]],

  // log(address,uint,uint,string)
  [2301889963, [address, uint256, uint256, string]],

  // log(address,uint256,uint256,uint256)
  [888202806, [address, uint256, uint256, uint256]],

  // log(address,uint,uint,uint)
  [1024368100, [address, uint256, uint256, uint256]],

  // log(bool,address,address,address)
  [487903233, [bool, address, address, address]],

  // log(bool,address,address,bool)
  [1180699616, [bool, address, address, bool]],

  // log(bool,address,address,string)
  [3625099623, [bool, address, address, string]],

  // log(bool,address,address,uint256)
  [208064958, [bool, address, address, uint256]],

  // log(bool,address,address,uint)
  [1384430956, [bool, address, address, uint256]],

  // log(bool,address,bool,address)
  [474063670, [bool, address, bool, address]],

  // log(bool,address,bool,bool)
  [1788626827, [bool, address, bool, bool]],

  // log(bool,address,bool,string)
  [1248250676, [bool, address, bool, string]],

  // log(bool,address,bool,uint256)
  [126031106, [bool, address, bool, uint256]],

  // log(bool,address,bool,uint)
  [1287000017, [bool, address, bool, uint256]],

  // log(bool,address,string,address)
  [1870422078, [bool, address, string, address]],

  // log(bool,address,string,bool)
  [3804222987, [bool, address, string, bool]],

  // log(bool,address,string,string)
  [2805734838, [bool, address, string, string]],

  // log(bool,address,string,uint256)
  [3256837319, [bool, address, string, uint256]],

  // log(bool,address,string,uint)
  [194640930, [bool, address, string, uint256]],

  // log(bool,address,uint256,address)
  [325780957, [bool, address, uint256, address]],

  // log(bool,address,uint,address)
  [1760647349, [bool, address, uint256, address]],

  // log(bool,address,uint256,bool)
  [3590430492, [bool, address, uint256, bool]],

  // log(bool,address,uint,bool)
  [4002252402, [bool, address, uint256, bool]],

  // log(bool,address,uint256,string)
  [1374724088, [bool, address, uint256, string]],

  // log(bool,address,uint,string)
  [2691192883, [bool, address, uint256, string]],

  // log(bool,address,uint256,uint256)
  [2079424929, [bool, address, uint256, uint256]],

  // log(bool,address,uint,uint)
  [2617143996, [bool, address, uint256, uint256]],

  // log(bool,bool,address,address)
  [4102557348, [bool, bool, address, address]],

  // log(bool,bool,address,bool)
  [3231908568, [bool, bool, address, bool]],

  // log(bool,bool,address,string)
  [2695133539, [bool, bool, address, string]],

  // log(bool,bool,address,uint256)
  [1276263767, [bool, bool, address, uint256]],

  // log(bool,bool,address,uint)
  [1620281063, [bool, bool, address, uint256]],

  // log(bool,bool,bool,address)
  [2352126746, [bool, bool, bool, address]],

  // log(bool,bool,bool,bool)
  [992632032, [bool, bool, bool, bool]],

  // log(bool,bool,bool,string)
  [719587540, [bool, bool, bool, string]],

  // log(bool,bool,bool,uint256)
  [1836074433, [bool, bool, bool, uint256]],

  // log(bool,bool,bool,uint)
  [3259532109, [bool, bool, bool, uint256]],

  // log(bool,bool,string,address)
  [4188875657, [bool, bool, string, address]],

  // log(bool,bool,string,bool)
  [3092715066, [bool, bool, string, bool]],

  // log(bool,bool,string,string)
  [1830717265, [bool, bool, string, string]],

  // log(bool,bool,string,uint256)
  [3819555375, [bool, bool, string, uint256]],

  // log(bool,bool,string,uint)
  [395003525, [bool, bool, string, uint256]],

  // log(bool,bool,uint256,address)
  [1420274080, [bool, bool, uint256, address]],

  // log(bool,bool,uint,address)
  [201299213, [bool, bool, uint256, address]],

  // log(bool,bool,uint256,bool)
  [1637764366, [bool, bool, uint256, bool]],

  // log(bool,bool,uint,bool)
  [2874982852, [bool, bool, uint256, bool]],

  // log(bool,bool,uint256,string)
  [2111099104, [bool, bool, uint256, string]],

  // log(bool,bool,uint,string)
  [1348569399, [bool, bool, uint256, string]],

  // log(bool,bool,uint256,uint256)
  [196087467, [bool, bool, uint256, uint256]],

  // log(bool,bool,uint,uint)
  [1181212302, [bool, bool, uint256, uint256]],

  // log(bool,string,address,address)
  [724244700, [bool, string, address, address]],

  // log(bool,string,address,bool)
  [1842623690, [bool, string, address, bool]],

  // log(bool,string,address,string)
  [316065672, [bool, string, address, string]],

  // log(bool,string,address,uint256)
  [2781534868, [bool, string, address, uint256]],

  // log(bool,string,address,uint)
  [453743963, [bool, string, address, uint256]],

  // log(bool,string,bool,address)
  [1401816747, [bool, string, bool, address]],

  // log(bool,string,bool,bool)
  [3697185627, [bool, string, bool, bool]],

  // log(bool,string,bool,string)
  [1211958294, [bool, string, bool, string]],

  // log(bool,string,bool,uint256)
  [369533843, [bool, string, bool, uint256]],

  // log(bool,string,bool,uint)
  [2372902053, [bool, string, bool, uint256]],

  // log(bool,string,string,address)
  [2547225816, [bool, string, string, address]],

  // log(bool,string,string,bool)
  [508266469, [bool, string, string, bool]],

  // log(bool,string,string,string)
  [392356650, [bool, string, string, string]],

  // log(bool,string,string,uint256)
  [2078327787, [bool, string, string, uint256]],

  // log(bool,string,string,uint)
  [1574643090, [bool, string, string, uint256]],

  // log(bool,string,uint256,address)
  [362193358, [bool, string, uint256, address]],

  // log(bool,string,uint,address)
  [1529002296, [bool, string, uint256, address]],

  // log(bool,string,uint256,bool)
  [1796103507, [bool, string, uint256, bool]],

  // log(bool,string,uint,bool)
  [549177775, [bool, string, uint256, bool]],

  // log(bool,string,uint256,string)
  [450457062, [bool, string, uint256, string]],

  // log(bool,string,uint,string)
  [2007084013, [bool, string, uint256, string]],

  // log(bool,string,uint256,uint256)
  [679886795, [bool, string, uint256, uint256]],

  // log(bool,string,uint,uint)
  [2387273838, [bool, string, uint256, uint256]],

  // log(bool,uint256,address,address)
  [653615272, [bool, uint256, address, address]],

  // log(bool,uint,address,address)
  [2318373034, [bool, uint256, address, address]],

  // log(bool,uint256,address,bool)
  [3032683775, [bool, uint256, address, bool]],

  // log(bool,uint,address,bool)
  [1705899016, [bool, uint256, address, bool]],

  // log(bool,uint256,address,string)
  [464760986, [bool, uint256, address, string]],

  // log(bool,uint,address,string)
  [403247937, [bool, uint256, address, string]],

  // log(bool,uint256,address,uint256)
  [355982471, [bool, uint256, address, uint256]],

  // log(bool,uint,address,uint)
  [3399820138, [bool, uint256, address, uint256]],

  // log(bool,uint256,bool,address)
  [2597139990, [bool, uint256, bool, address]],

  // log(bool,uint,bool,address)
  [1114097656, [bool, uint256, bool, address]],

  // log(bool,uint256,bool,bool)
  [3468031191, [bool, uint256, bool, bool]],

  // log(bool,uint,bool,bool)
  [2650928961, [bool, uint256, bool, bool]],

  // log(bool,uint256,bool,string)
  [2437143473, [bool, uint256, bool, string]],

  // log(bool,uint,bool,string)
  [3067439572, [bool, uint256, bool, string]],

  // log(bool,uint256,bool,uint256)
  [2140912802, [bool, uint256, bool, uint256]],

  // log(bool,uint,bool,uint)
  [3554563475, [bool, uint256, bool, uint256]],

  // log(bool,uint256,string,address)
  [4275904511, [bool, uint256, string, address]],

  // log(bool,uint,string,address)
  [2781285673, [bool, uint256, string, address]],

  // log(bool,uint256,string,bool)
  [3857124139, [bool, uint256, string, bool]],

  // log(bool,uint,string,bool)
  [2446522387, [bool, uint256, string, bool]],

  // log(bool,uint256,string,string)
  [4122747465, [bool, uint256, string, string]],

  // log(bool,uint,string,string)
  [3542771016, [bool, uint256, string, string]],

  // log(bool,uint256,string,uint256)
  [1779538402, [bool, uint256, string, uint256]],

  // log(bool,uint,string,uint)
  [1098907931, [bool, uint256, string, uint256]],

  // log(bool,uint256,uint256,address)
  [14518201, [bool, uint256, uint256, address]],

  // log(bool,uint,uint,address)
  [4049711649, [bool, uint256, uint256, address]],

  // log(bool,uint256,uint256,bool)
  [3197649747, [bool, uint256, uint256, bool]],

  // log(bool,uint,uint,bool)
  [2753397214, [bool, uint256, uint256, bool]],

  // log(bool,uint256,uint256,string)
  [2389310301, [bool, uint256, uint256, string]],

  // log(bool,uint,uint,string)
  [3657852616, [bool, uint256, uint256, string]],

  // log(bool,uint256,uint256,uint256)
  [927708338, [bool, uint256, uint256, uint256]],

  // log(bool,uint,uint,uint)
  [853517604, [bool, uint256, uint256, uint256]],

  // log(string,address,address,address)
  [3985582326, [string, address, address, address]],

  // log(string,address,address,bool)
  [3047013728, [string, address, address, bool]],

  // log(string,address,address,string)
  [2148146279, [string, address, address, string]],

  // log(string,address,address,uint256)
  [2398352281, [string, address, address, uint256]],

  // log(string,address,address,uint)
  [1857524797, [string, address, address, uint256]],

  // log(string,address,bool,address)
  [573965245, [string, address, bool, address]],

  // log(string,address,bool,bool)
  [2038975531, [string, address, bool, bool]],

  // log(string,address,bool,string)
  [72663161, [string, address, bool, string]],

  // log(string,address,bool,uint256)
  [1050642026, [string, address, bool, uint256]],

  // log(string,address,bool,uint)
  [3318856587, [string, address, bool, uint256]],

  // log(string,address,string,address)
  [2864486961, [string, address, string, address]],

  // log(string,address,string,bool)
  [1595265676, [string, address, string, bool]],

  // log(string,address,string,string)
  [609847026, [string, address, string, string]],

  // log(string,address,string,uint256)
  [2446397742, [string, address, string, uint256]],

  // log(string,address,string,uint)
  [2405583849, [string, address, string, uint256]],

  // log(string,address,uint256,address)
  [1677429701, [string, address, uint256, address]],

  // log(string,address,uint,address)
  [2741431424, [string, address, uint256, address]],

  // log(string,address,uint256,bool)
  [4232594928, [string, address, uint256, bool]],

  // log(string,address,uint,bool)
  [1522647356, [string, address, uint256, bool]],

  // log(string,address,uint256,string)
  [1514632754, [string, address, uint256, string]],

  // log(string,address,uint,string)
  [1280700980, [string, address, uint256, string]],

  // log(string,address,uint256,uint256)
  [4176812830, [string, address, uint256, uint256]],

  // log(string,address,uint,uint)
  [3668153533, [string, address, uint256, uint256]],

  // log(string,bool,address,address)
  [870964509, [string, bool, address, address]],

  // log(string,bool,address,bool)
  [2508990662, [string, bool, address, bool]],

  // log(string,bool,address,string)
  [764294052, [string, bool, address, string]],

  // log(string,bool,address,uint256)
  [1560853253, [string, bool, address, uint256]],

  // log(string,bool,address,uint)
  [685723286, [string, bool, address, uint256]],

  // log(string,bool,bool,address)
  [1905304873, [string, bool, bool, address]],

  // log(string,bool,bool,bool)
  [2304440517, [string, bool, bool, bool]],

  // log(string,bool,bool,string)
  [2636305885, [string, bool, bool, string]],

  // log(string,bool,bool,uint256)
  [2386524329, [string, bool, bool, uint256]],

  // log(string,bool,bool,uint)
  [2155164136, [string, bool, bool, uint256]],

  // log(string,bool,string,address)
  [3764542249, [string, bool, string, address]],

  // log(string,bool,string,bool)
  [1066037277, [string, bool, string, bool]],

  // log(string,bool,string,string)
  [2821114603, [string, bool, string, string]],

  // log(string,bool,string,uint256)
  [620303461, [string, bool, string, uint256]],

  // log(string,bool,string,uint)
  [885731469, [string, bool, string, uint256]],

  // log(string,bool,uint256,address)
  [2472413631, [string, bool, uint256, address]],

  // log(string,bool,uint,address)
  [1909687565, [string, bool, uint256, address]],

  // log(string,bool,uint256,bool)
  [2331496330, [string, bool, uint256, bool]],

  // log(string,bool,uint,bool)
  [1019590099, [string, bool, uint256, bool]],

  // log(string,bool,uint256,string)
  [1949134567, [string, bool, uint256, string]],

  // log(string,bool,uint,string)
  [1119461927, [string, bool, uint256, string]],

  // log(string,bool,uint256,uint256)
  [1689631591, [string, bool, uint256, uint256]],

  // log(string,bool,uint,uint)
  [1572859960, [string, bool, uint256, uint256]],

  // log(string,string,address,address)
  [1134328815, [string, string, address, address]],

  // log(string,string,address,bool)
  [1556958775, [string, string, address, bool]],

  // log(string,string,address,string)
  [3944480640, [string, string, address, string]],

  // log(string,string,address,uint256)
  [2093204999, [string, string, address, uint256]],

  // log(string,string,address,uint)
  [1250010474, [string, string, address, uint256]],

  // log(string,string,bool,address)
  [3279013851, [string, string, bool, address]],

  // log(string,string,bool,bool)
  [1081628777, [string, string, bool, bool]],

  // log(string,string,bool,string)
  [1585754346, [string, string, bool, string]],

  // log(string,string,bool,uint256)
  [3601791698, [string, string, bool, uint256]],

  // log(string,string,bool,uint)
  [2256636538, [string, string, bool, uint256]],

  // log(string,string,string,address)
  [1834430276, [string, string, string, address]],

  // log(string,string,string,bool)
  [739726573, [string, string, string, bool]],

  // log(string,string,string,string)
  [3731419658, [string, string, string, string]],

  // log(string,string,string,uint256)
  [2393878571, [string, string, string, uint256]],

  // log(string,string,string,uint)
  [2681211381, [string, string, string, uint256]],

  // log(string,string,uint256,address)
  [270792626, [string, string, uint256, address]],

  // log(string,string,uint,address)
  [1565476480, [string, string, uint256, address]],

  // log(string,string,uint256,bool)
  [3282609748, [string, string, uint256, bool]],

  // log(string,string,uint,bool)
  [3864418506, [string, string, uint256, bool]],

  // log(string,string,uint256,string)
  [1562023706, [string, string, uint256, string]],

  // log(string,string,uint,string)
  [2366909661, [string, string, uint256, string]],

  // log(string,string,uint256,uint256)
  [4099767596, [string, string, uint256, uint256]],

  // log(string,string,uint,uint)
  [3587119056, [string, string, uint256, uint256]],

  // log(string,uint256,address,address)
  [1587722158, [string, uint256, address, address]],

  // log(string,uint,address,address)
  [3939013249, [string, uint256, address, address]],

  // log(string,uint256,address,bool)
  [2182163010, [string, uint256, address, bool]],

  // log(string,uint,address,bool)
  [285649143, [string, uint256, address, bool]],

  // log(string,uint256,address,string)
  [2684039059, [string, uint256, address, string]],

  // log(string,uint,address,string)
  [844415720, [string, uint256, address, string]],

  // log(string,uint256,address,uint256)
  [1325727174, [string, uint256, address, uint256]],

  // log(string,uint,address,uint)
  [1481210622, [string, uint256, address, uint256]],

  // log(string,uint256,bool,address)
  [3773389720, [string, uint256, bool, address]],

  // log(string,uint,bool,address)
  [3847527825, [string, uint256, bool, address]],

  // log(string,uint256,bool,bool)
  [894187222, [string, uint256, bool, bool]],

  // log(string,uint,bool,bool)
  [3816813520, [string, uint256, bool, bool]],

  // log(string,uint256,bool,string)
  [2885106328, [string, uint256, bool, string]],

  // log(string,uint,bool,string)
  [1993105508, [string, uint256, bool, string]],

  // log(string,uint256,bool,uint256)
  [3827003247, [string, uint256, bool, uint256]],

  // log(string,uint,bool,uint)
  [1427009269, [string, uint256, bool, uint256]],

  // log(string,uint256,string,address)
  [2084975268, [string, uint256, string, address]],

  // log(string,uint,string,address)
  [3144824297, [string, uint256, string, address]],

  // log(string,uint256,string,bool)
  [2099530013, [string, uint256, string, bool]],

  // log(string,uint,string,bool)
  [3919545039, [string, uint256, string, bool]],

  // log(string,uint256,string,string)
  [1522028063, [string, uint256, string, string]],

  // log(string,uint,string,string)
  [1821956834, [string, uint256, string, string]],

  // log(string,uint256,string,uint256)
  [3330189777, [string, uint256, string, uint256]],

  // log(string,uint,string,uint)
  [2697245221, [string, uint256, string, uint256]],

  // log(string,uint256,uint256,address)
  [3793609336, [string, uint256, uint256, address]],

  // log(string,uint,uint,address)
  [3201771711, [string, uint256, uint256, address]],

  // log(string,uint256,uint256,bool)
  [1982258066, [string, uint256, uint256, bool]],

  // log(string,uint,uint,bool)
  [4147936829, [string, uint256, uint256, bool]],

  // log(string,uint256,uint256,string)
  [2236298390, [string, uint256, uint256, string]],

  // log(string,uint,uint,string)
  [2773406909, [string, uint256, uint256, string]],

  // log(string,uint256,uint256,uint256)
  [2812835923, [string, uint256, uint256, uint256]],

  // log(string,uint,uint,uint)
  [149837414, [string, uint256, uint256, uint256]],

  // log(uint256,address,address,address)
  [612938772, [uint256, address, address, address]],

  // log(uint,address,address,address)
  [1430734329, [uint256, address, address, address]],

  // log(uint256,address,address,bool)
  [153090805, [uint256, address, address, bool]],

  // log(uint,address,address,bool)
  [22350596, [uint256, address, address, bool]],

  // log(uint256,address,address,string)
  [52195187, [uint256, address, address, string]],

  // log(uint,address,address,string)
  [2034490470, [uint256, address, address, string]],

  // log(uint256,address,address,uint256)
  [1936653238, [uint256, address, address, uint256]],

  // log(uint,address,address,uint)
  [2587672470, [uint256, address, address, uint256]],

  // log(uint256,address,bool,address)
  [4017276179, [uint256, address, bool, address]],

  // log(uint,address,bool,address)
  [3056677012, [uint256, address, bool, address]],

  // log(uint256,address,bool,bool)
  [3813741583, [uint256, address, bool, bool]],

  // log(uint,address,bool,bool)
  [2116501773, [uint256, address, bool, bool]],

  // log(uint256,address,bool,string)
  [2432370346, [uint256, address, bool, string]],

  // log(uint,address,bool,string)
  [1676730946, [uint256, address, bool, string]],

  // log(uint256,address,bool,uint256)
  [1522374954, [uint256, address, bool, uint256]],

  // log(uint,address,bool,uint)
  [2064181483, [uint256, address, bool, uint256]],

  // log(uint256,address,string,address)
  [2629472255, [uint256, address, string, address]],

  // log(uint,address,string,address)
  [3420819197, [uint256, address, string, address]],

  // log(uint256,address,string,bool)
  [3425872647, [uint256, address, string, bool]],

  // log(uint,address,string,bool)
  [581204390, [uint256, address, string, bool]],

  // log(uint256,address,string,string)
  [1041403043, [uint256, address, string, string]],

  // log(uint,address,string,string)
  [2373420580, [uint256, address, string, string]],

  // log(uint256,address,string,uint256)
  [1182952285, [uint256, address, string, uint256]],

  // log(uint,address,string,uint)
  [2697204968, [uint256, address, string, uint256]],

  // log(uint256,address,uint256,address)
  [364980149, [uint256, address, uint256, address]],

  // log(uint,address,uint,address)
  [4256361684, [uint256, address, uint256, address]],

  // log(uint256,address,uint256,bool)
  [1601452668, [uint256, address, uint256, bool]],

  // log(uint,address,uint,bool)
  [435581801, [uint256, address, uint256, bool]],

  // log(uint256,address,uint256,string)
  [3719324961, [uint256, address, uint256, string]],

  // log(uint,address,uint,string)
  [1054063912, [uint256, address, uint256, string]],

  // log(uint256,address,uint256,uint256)
  [211605953, [uint256, address, uint256, uint256]],

  // log(uint,address,uint,uint)
  [3399106228, [uint256, address, uint256, uint256]],

  // log(uint256,bool,address,address)
  [2716814523, [uint256, bool, address, address]],

  // log(uint,bool,address,address)
  [2263728396, [uint256, bool, address, address]],

  // log(uint256,bool,address,bool)
  [1162695845, [uint256, bool, address, bool]],

  // log(uint,bool,address,bool)
  [2449150530, [uint256, bool, address, bool]],

  // log(uint256,bool,address,string)
  [2917159623, [uint256, bool, address, string]],

  // log(uint,bool,address,string)
  [2721084958, [uint256, bool, address, string]],

  // log(uint256,bool,address,uint256)
  [125994997, [uint256, bool, address, uint256]],

  // log(uint,bool,address,uint)
  [1102442299, [uint256, bool, address, uint256]],

  // log(uint256,bool,bool,address)
  [1768164185, [uint256, bool, bool, address]],

  // log(uint,bool,bool,address)
  [1392910941, [uint256, bool, bool, address]],

  // log(uint256,bool,bool,bool)
  [3069540257, [uint256, bool, bool, bool]],

  // log(uint,bool,bool,bool)
  [1315722005, [uint256, bool, bool, bool]],

  // log(uint256,bool,bool,string)
  [3722155361, [uint256, bool, bool, string]],

  // log(uint,bool,bool,string)
  [831186331, [uint256, bool, bool, string]],

  // log(uint256,bool,bool,uint256)
  [1952763427, [uint256, bool, bool, uint256]],

  // log(uint,bool,bool,uint)
  [3173363033, [uint256, bool, bool, uint256]],

  // log(uint256,bool,string,address)
  [4015165464, [uint256, bool, string, address]],

  // log(uint,bool,string,address)
  [1231956916, [uint256, bool, string, address]],

  // log(uint256,bool,string,bool)
  [3952250239, [uint256, bool, string, bool]],

  // log(uint,bool,string,bool)
  [879671495, [uint256, bool, string, bool]],

  // log(uint256,bool,string,string)
  [1757984957, [uint256, bool, string, string]],

  // log(uint,bool,string,string)
  [2754870525, [uint256, bool, string, string]],

  // log(uint256,bool,string,uint256)
  [740099910, [uint256, bool, string, uint256]],

  // log(uint,bool,string,uint)
  [2438978344, [uint256, bool, string, uint256]],

  // log(uint256,bool,uint256,address)
  [2295029825, [uint256, bool, uint256, address]],

  // log(uint,bool,uint,address)
  [1329595790, [uint256, bool, uint256, address]],

  // log(uint256,bool,uint256,bool)
  [2443193898, [uint256, bool, uint256, bool]],

  // log(uint,bool,uint,bool)
  [3534472445, [uint256, bool, uint256, bool]],

  // log(uint256,bool,uint256,string)
  [3724797812, [uint256, bool, uint256, string]],

  // log(uint,bool,uint,string)
  [3906845782, [uint256, bool, uint256, string]],

  // log(uint256,bool,uint256,uint256)
  [3333212072, [uint256, bool, uint256, uint256]],

  // log(uint,bool,uint,uint)
  [1451396516, [uint256, bool, uint256, uint256]],

  // log(uint256,string,address,address)
  [1634266465, [uint256, string, address, address]],

  // log(uint,string,address,address)
  [2141537675, [uint256, string, address, address]],

  // log(uint256,string,address,bool)
  [2428701270, [uint256, string, address, bool]],

  // log(uint,string,address,bool)
  [4181720887, [uint256, string, address, bool]],

  // log(uint256,string,address,string)
  [2621104033, [uint256, string, address, string]],

  // log(uint,string,address,string)
  [4170733439, [uint256, string, address, string]],

  // log(uint256,string,address,uint256)
  [3906142605, [uint256, string, address, uint256]],

  // log(uint,string,address,uint)
  [2565338099, [uint256, string, address, uint256]],

  // log(uint256,string,bool,address)
  [2922300801, [uint256, string, bool, address]],

  // log(uint,string,bool,address)
  [2037328032, [uint256, string, bool, address]],

  // log(uint256,string,bool,bool)
  [3126025628, [uint256, string, bool, bool]],

  // log(uint,string,bool,bool)
  [1371286465, [uint256, string, bool, bool]],

  // log(uint256,string,bool,string)
  [3537118157, [uint256, string, bool, string]],

  // log(uint,string,bool,string)
  [2370346144, [uint256, string, bool, string]],

  // log(uint256,string,bool,uint256)
  [3472922752, [uint256, string, bool, uint256]],

  // log(uint,string,bool,uint)
  [2763295359, [uint256, string, bool, uint256]],

  // log(uint256,string,string,address)
  [3582182914, [uint256, string, string, address]],

  // log(uint,string,string,address)
  [3432549024, [uint256, string, string, address]],

  // log(uint256,string,string,bool)
  [3014047421, [uint256, string, string, bool]],

  // log(uint,string,string,bool)
  [310782872, [uint256, string, string, bool]],

  // log(uint256,string,string,string)
  [564987523, [uint256, string, string, string]],

  // log(uint,string,string,string)
  [1474103825, [uint256, string, string, string]],

  // log(uint256,string,string,uint256)
  [2955463101, [uint256, string, string, uint256]],

  // log(uint,string,string,uint)
  [1995203422, [uint256, string, string, uint256]],

  // log(uint256,string,uint256,address)
  [992115124, [uint256, string, uint256, address]],

  // log(uint,string,uint,address)
  [2877020669, [uint256, string, uint256, address]],

  // log(uint256,string,uint256,bool)
  [1763348340, [uint256, string, uint256, bool]],

  // log(uint,string,uint,bool)
  [2270850606, [uint256, string, uint256, bool]],

  // log(uint256,string,uint256,string)
  [3082360010, [uint256, string, uint256, string]],

  // log(uint,string,uint,string)
  [2730232985, [uint256, string, uint256, string]],

  // log(uint256,string,uint256,uint256)
  [2193775476, [uint256, string, uint256, uint256]],

  // log(uint,string,uint,uint)
  [3221501959, [uint256, string, uint256, uint256]],

  // log(uint256,uint256,address,address)
  [1453707697, [uint256, uint256, address, address]],

  // log(uint,uint,address,address)
  [3398671136, [uint256, uint256, address, address]],

  // log(uint256,uint256,address,bool)
  [365610102, [uint256, uint256, address, bool]],

  // log(uint,uint,address,bool)
  [2833785006, [uint256, uint256, address, bool]],

  // log(uint256,uint256,address,string)
  [1826504888, [uint256, uint256, address, string]],

  // log(uint,uint,address,string)
  [3600994782, [uint256, uint256, address, string]],

  // log(uint256,uint256,address,uint256)
  [2297881778, [uint256, uint256, address, uint256]],

  // log(uint,uint,address,uint)
  [1628154048, [uint256, uint256, address, uint256]],

  // log(uint256,uint256,bool,address)
  [2592172675, [uint256, uint256, bool, address]],

  // log(uint,uint,bool,address)
  [3776410703, [uint256, uint256, bool, address]],

  // log(uint256,uint256,bool,bool)
  [2869451494, [uint256, uint256, bool, bool]],

  // log(uint,uint,bool,bool)
  [2495495089, [uint256, uint256, bool, bool]],

  // log(uint256,uint256,bool,string)
  [2780101785, [uint256, uint256, bool, string]],

  // log(uint,uint,bool,string)
  [4024028142, [uint256, uint256, bool, string]],

  // log(uint256,uint256,bool,uint256)
  [3950997458, [uint256, uint256, bool, uint256]],

  // log(uint,uint,bool,uint)
  [1818524812, [uint256, uint256, bool, uint256]],

  // log(uint256,uint256,string,address)
  [1121066423, [uint256, uint256, string, address]],

  // log(uint,uint,string,address)
  [1127384482, [uint256, uint256, string, address]],

  // log(uint256,uint256,string,bool)
  [2062986021, [uint256, uint256, string, bool]],

  // log(uint,uint,string,bool)
  [2989403910, [uint256, uint256, string, bool]],

  // log(uint256,uint256,string,string)
  [668512210, [uint256, uint256, string, string]],

  // log(uint,uint,string,string)
  [2080582194, [uint256, uint256, string, string]],

  // log(uint256,uint256,string,uint256)
  [1570936811, [uint256, uint256, string, uint256]],

  // log(uint,uint,string,uint)
  [949229117, [uint256, uint256, string, uint256]],

  // log(uint256,uint256,uint256,address)
  [4202792367, [uint256, uint256, uint256, address]],

  // log(uint,uint,uint,address)
  [3766828905, [uint256, uint256, uint256, address]],

  // log(uint256,uint256,uint256,bool)
  [3315126661, [uint256, uint256, uint256, bool]],

  // log(uint,uint,uint,bool)
  [1683143115, [uint256, uint256, uint256, bool]],

  // log(uint256,uint256,uint256,string)
  [1506790371, [uint256, uint256, uint256, string]],

  // log(uint,uint,uint,string)
  [2024634892, [uint256, uint256, uint256, string]],

  // log(uint256,uint256,uint256,uint256)
  [423606272, [uint256, uint256, uint256, uint256]],

  // log(uint,uint,uint,uint)
  [1554033982, [uint256, uint256, uint256, uint256]]
]);
