name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches: [chore/automate-publishing]
#  release:
#    types: [published]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    name: Push Docker image to Docker Hub
    steps:
      - name: Get release VERSION
        run: VERSION="test-version@1"

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.TEMP_DOCKER_USERNAME }}
          password: ${{ secrets.TEMP_DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: micaiahreid/test-publish

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
