name: Publish Docker image

on:
  push:
    branches: [chore/automate-publishing]
#  release:
#    types: [published]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    name: Push Docker image to Docker Hub
    steps:
      - name: Get release VERSION
        run: VERSION=$(node -e 'console.log(require("./src/packages/ganache/package.json").version)')

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: trufflesuite/ganache-core

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ganache@${VERSION}
          labels: ${{ steps.meta.outputs.labels }}
