name: Test Publish Docker

on: push

jobs:
  publish-docker:
    runs-on: ubuntu-20.04
    steps:
      # because the docker publish action is an action we made, we have to
      # check out the repo
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Ganache's docker publish action
        uses: ./.github/actions/docker-publish
        with:
          VERSION: ${{ env.VERSION }}
          TAG: ${{ env.TAG }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          INFURA_KEY: ${{ secrets.INFURA_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
