name: Test Publish Docker

on: push

jobs:
  publish-docker:
    runs-on: ubuntu-20.04
    steps:
      # because the docker publish action is an action we made, we have to
      # check out the repo
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Ganache's docker publish action
        uses: ./
        id: action
        with:
          VERSION: env.VERSION
          TAG: env.TAG
